version: "3"

services: 
    app:
        build:
            context: .
        ports: 
            - "8000:8000" # Mapping our project from port 8000 on our host to port 8000 on our image 
        # the volume allows us to get the updates that we make to our project in real time.
        volumes: 
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
            